---
apiVersion: apps/v1beta2 # for versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: sevis-challenge-front
  labels:
    app: sevis-challenge-front
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sevis-challenge-front
      tier: app
  template:
    metadata:
      name: sevis-challenge-front
      labels:
        app: sevis-challenge-front
        tier: app
    spec:
      containers:
      - name: sevis-challenge-front
        image: 036167247202.dkr.ecr.us-east-1.amazonaws.com/sevis-challenge-front:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 4200
