---
apiVersion: v1
kind: Service
metadata:
  name: sevis-challenge-front
  labels:
    app: sevis-challenge-front
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  # type: NodePort
  # ports:
  # - port: 8080
  #   targetPort: 8080
  #   protocol: TCP
  #   nodePort: 31111
  selector:
    app: sevis-challenge-front
    tier: app
